{
 "title": "Home",
 "time": { "from": "2022-02-01T00:00:00.000Z", "to": "2022-02-27T00:00:00.000Z" },
 "panels": [
  {
   "title": "Prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "type": "welcome",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gettingstarted",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest from the blog",
   "type": "news",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {}
   ]
  }
 ]
}